### ISSUE TITLE
Question : Expansion

### ISSUE THREAD

**Issue by Clueless-AI** [BarutSRB/LA_Overlay#4]
Hello, 
Do you guys have any plans of adding more classes to the Overlay ? as a WoW player I'm used to having my Weakauras in the center of the screen and this will help a lot in Lost Ark. 
Thanks

**Comment by BarutSRB** [comment]
I only play Bards, but you can customize it for any class you like. Simply modify the settings.py file and place your skill icons in the designated folder. The process is quite straightforward.

**Comment by Clueless-AI** [comment]
I'll give it a look, thank you
